[package]
name = "clob-engine"
version = "0.1.3"
edition = "2024"
description = "Low-latency CLOB"
license = "MIT"

[dependencies]
anyhow = "1.0.100"
tracing = "0.1.44"
uuid = {version = "1.19.0", features = ['v4']}
